### ISSUE TITLE
NPE on startup when config doesn't exist

### ISSUE THREAD

**Issue by BlackXnt** [Civcraft/PrisonPearl#106]
[20:18:34 ERROR]: Error occurred while enabling PrisonPearl v3.0.27 (Is it up to date?)
java.lang.NullPointerException
        at vg.civcraft.mc.prisonpearl.PrisonPearlConfig.getUsername(PrisonPearlConfig.java:43) ~[?:?]
        at vg.civcraft.mc.prisonpearl.database.mysql.MysqlDatabaseHandler.initializeDB(MysqlDatabaseHandler.java:38) ~[?:?]
        at vg.civcraft.mc.prisonpearl.database.mysql.MysqlDatabaseHandler.<init>(MysqlDatabaseHandler.java:32) ~[?:?]
        at vg.civcraft.mc.prisonpearl.database.DataBaseHandler.handleMysql(DataBaseHandler.java:61) ~[?:?]
        at vg.civcraft.mc.prisonpearl.database.DataBaseHandler.<init>(DataBaseHandler.java:39) ~[?:?]
        at vg.civcraft.mc.prisonpearl.PrisonPearlPlugin.onEnable(PrisonPearlPlugin.java:51) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-07c3001]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]

**Comment by BlackXnt** [comment]
Issue seems to be fixed by upgrading to the newest version of CivModCore.
