### ISSUE TITLE
Stack

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/PrisonPearl#125]
[19:16:55 ERROR]: Could not pass event AsyncPluginBroadcastMessageEvent to PrisonPearl v3.0.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-880a532]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-880a532]
        at vg.civcraft.mc.mercury.events.BukkitEventManager.fireMessage(BukkitEventManager.java:11) [Mercury-1.1.112.jar:?]
        at vg.civcraft.mc.mercury.events.EventManager.fireMessage(EventManager.java:15) [Mercury-1.1.112.jar:?]
        at vg.civcraft.mc.mercury.rabbitmq.RabbitConsumer.handleDelivery(RabbitConsumer.java:83) [Mercury-1.1.112.jar:?]
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144) [Mercury-1.1.112.jar:?]
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99) [Mercury-1.1.112.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72-internal]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.IllegalStateException: Asynchronous entity add!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1003) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.World.addEntity(World.java:999) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.dropItem(CraftWorld.java:313) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.dropItemNaturally(CraftWorld.java:352) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at vg.civcraft.mc.prisonpearl.PrisonPearlUtil.dropInventory(PrisonPearlUtil.java:208) ~[?:?]
        at vg.civcraft.mc.prisonpearl.PrisonPearlUtil.respawnPlayerCorrectly(PrisonPearlUtil.java:84) ~[?:?]
        at vg.civcraft.mc.prisonpearl.PrisonPearlUtil.respawnPlayerCorrectly(PrisonPearlUtil.java:39) ~[?:?]
        at vg.civcraft.mc.prisonpearl.managers.SummonManager.summonPlayer(SummonManager.java:68) ~[?:?]
        at vg.civcraft.mc.prisonpearl.listener.MercuryListener.prisonPearlSummon(MercuryListener.java:174) ~[?:?]
        at vg.civcraft.mc.prisonpearl.listener.MercuryListener.mercuryListener(MercuryListener.java:60) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-880a532]
        ... 11 more

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/commit/56ba889263c5cc56f458dcd82ad760867d2fdbd6
