### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/PrisonPearl#126]
[19:12:32 WARN]: [PrisonPearl] Task #6370 for PrisonPearl v3.0.4 generated an exception
java.lang.ClassCastException: org.bukkit.Location cannot be cast to vg.civcraft.mc.prisonpearl.misc.FakeLocation
        at vg.civcraft.mc.prisonpearl.PrisonPearlUtil.respawnPlayerCorrectly(PrisonPearlUtil.java:76) ~[?:?]
        at vg.civcraft.mc.prisonpearl.PrisonPearlUtil.respawnPlayerCorrectly(PrisonPearlUtil.java:39) ~[?:?]
        at vg.civcraft.mc.prisonpearl.listener.PlayerListener$1.run(PlayerListener.java:154) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]

**Comment by Maxopoly** [comment]
Duplicate for https://github.com/Civcraft/PrisonPearl/issues/109

**Comment by rourke750** [comment]
Are the stacks for sure the same?

**Comment by Maxopoly** [comment]
Think so, it's just a slightly different line because you changed stuff in the mean time.

**Comment by rourke750** [comment]
Can we keep the most recent stack.

**Comment by ttk2** [comment]
so which of these issues are we keeping?

**Comment by rourke750** [comment]
Unable to reproduce.

**Comment by rourke750** [comment]
Don't believe this to be the case anymore.  Will reopen if it comes back again.

**Comment by Maxopoly** [comment]
Kinda still happening

https://log.civcraft.co/search?rangetype=absolute&fields=message%2Csource&width=1920&from=2016-03-26T22%3A47%3A44.950Z&to=2016-03-26T22%3A47%3A46.950Z&q=NOT+source%3Anginx+AND+source_file%3A%5C%2Fhome%5C%2Fcivcraft%5C-admins%5C%2FShards%5C%2FAleph%5C%2Flogs%5C%2Flatest.log#fields=message%2Csource

**Comment by Maxopoly** [comment]
[19:56:14 INFO]: GameNBurger issued server command: /ppreturn                                                                                                                                                                        [0/9357]
[19:56:14 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ppreturn' in plugin PrisonPearl v3.0.49
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-880a532]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.ClassCastException: org.bukkit.Location cannot be cast to vg.civcraft.mc.prisonpearl.misc.FakeLocation
        at vg.civcraft.mc.prisonpearl.PrisonPearlUtil.respawnPlayerCorrectly(PrisonPearlUtil.java:79) ~[?:?]
        at vg.civcraft.mc.prisonpearl.PrisonPearlUtil.respawnPlayerCorrectly(PrisonPearlUtil.java:42) ~[?:?]
        at vg.civcraft.mc.prisonpearl.managers.SummonManager.returnPlayer(SummonManager.java:91) ~[?:?]
        at vg.civcraft.mc.prisonpearl.command.commands.Return.execute(Return.java:52) ~[?:?]
        at vg.civcraft.mc.civmodcore.command.CommandHandler.execute(CommandHandler.java:26) ~[?:?]
        at vg.civcraft.mc.civmodcore.ACivMod.onCommand(ACivMod.java:64) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-db6de12-880a532]
        ... 15 more


Just now
