### ISSUE TITLE
Player still Dead Exception

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/PrisonPearl#158]
[22:25:30 WARN]: vg.civcraft.mc.bettershards.misc.PlayerStillDeadException
[22:25:30 WARN]:        at vg.civcraft.mc.bettershards.manager.ConnectionManager.teleportPlayerToServer(ConnectionManager.java:83)
[22:25:30 WARN]:        at vg.civcraft.mc.bettershards.BetterShardsAPI.connectPlayer(BetterShardsAPI.java:25)
[22:25:30 WARN]:        at vg.civcraft.mc.prisonpearl.PrisonPearlUtilShards.respawnPlayerCorrectlyShards(PrisonPearlUtilShards.java:63)
[22:25:30 WARN]:        at vg.civcraft.mc.prisonpearl.PrisonPearlUtil.respawnPlayerCorrectly(PrisonPearlUtil.java:59)
[22:25:30 WARN]:        at vg.civcraft.mc.prisonpearl.PrisonPearlUtil.respawnPlayerCorrectly(PrisonPearlUtil.java:40)
[22:25:30 WARN]:        at vg.civcraft.mc.prisonpearl.managers.SummonManager.returnPlayer(SummonManager.java:97)
[22:25:30 WARN]:        at vg.civcraft.mc.prisonpearl.managers.SummonManager.returnPlayer(SummonManager.java:89)
[22:25:30 WARN]:        at vg.civcraft.mc.prisonpearl.listener.PlayerListener.onPlayerRespawn(PlayerListener.java:169)
[22:25:30 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:25:30 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:25:30 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:25:30 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[22:25:30 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[22:25:30 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:25:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[22:25:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[22:25:30 WARN]:        at net.minecraft.server.v1_10_R1.PlayerList.moveToWorld(PlayerList.java:629)
[22:25:30 WARN]:        at net.minecraft.server.v1_10_R1.PlayerList.moveToWorld(PlayerList.java:558)
[22:25:30 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1607)
[22:25:30 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInClientCommand.a(SourceFile:31)
[22:25:30 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInClientCommand.a(SourceFile:8)
[22:25:30 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:25:30 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:25:30 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:25:30 WARN]:        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[22:25:30 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[22:25:30 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[22:25:30 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[22:25:30 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[22:25:30 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by rourke750** [comment]
Everything has been reworked here https://github.com/Civcraft/PrisonPearl/pull/174
