### ISSUE TITLE
Summoning a player fails if he is already in the same shard

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/PrisonPearl#162]
org.bukkit.command.CommandException: Unhandled exception executing command 'pps' in plugin PrisonPearl v3.0.94
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassCastException: org.bukkit.Location cannot be cast to vg.civcraft.mc.prisonpearl.misc.FakeLocation
        at vg.civcraft.mc.prisonpearl.PrisonPearlUtilShards.respawnPlayerCorrectlyShards(PrisonPearlUtilShards.java:68) ~[?:?]
        at vg.civcraft.mc.prisonpearl.PrisonPearlUtil.respawnPlayerCorrectly(PrisonPearlUtil.java:59) ~[?:?]
        at vg.civcraft.mc.prisonpearl.PrisonPearlUtil.respawnPlayerCorrectly(PrisonPearlUtil.java:36) ~[?:?]
        at vg.civcraft.mc.prisonpearl.managers.SummonManager.summonPlayer(SummonManager.java:70) ~[?:?]
        at vg.civcraft.mc.prisonpearl.command.commands.SummonCommand.execute(SummonCommand.java:46) ~[?:?]
        at vg.civcraft.mc.civmodcore.command.CommandHandler.execute(CommandHandler.java:26) ~[?:?]
        at vg.civcraft.mc.civmodcore.ACivMod.onCommand(ACivMod.java:66) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
        ... 15 more

**Comment by rourke750** [comment]
Fixed latest commit https://github.com/Civcraft/PrisonPearl/pull/174
