### ISSUE TITLE
Stack on PP return

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/PrisonPearl#163]
Happened after /pps was attempted while prisoner was already in the same shard. Using pps again would say the player is already summoned, ppr did this:

[22:36:44 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ppr' in plugin PrisonPearl v3.0.94
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-e0e1771-5e5cf84]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassCastException: org.bukkit.Location cannot be cast to vg.civcraft.mc.prisonpearl.misc.FakeLocation
        at vg.civcraft.mc.prisonpearl.PrisonPearlUtilShards.respawnPlayerCorrectlyShards(PrisonPearlUtilShards.java:59) ~[?:?]
        at vg.civcraft.mc.prisonpearl.PrisonPearlUtil.respawnPlayerCorrectly(PrisonPearlUtil.java:59) ~[?:?]
        at vg.civcraft.mc.prisonpearl.PrisonPearlUtil.respawnPlayerCorrectly(PrisonPearlUtil.java:40) ~[?:?]
        at vg.civcraft.mc.prisonpearl.managers.SummonManager.returnPlayer(SummonManager.java:97) ~[?:?]
        at vg.civcraft.mc.prisonpearl.managers.SummonManager.returnPlayer(SummonManager.java:89) ~[?:?]
        at vg.civcraft.mc.prisonpearl.command.commands.Return.execute(Return.java:61) ~[?:?]
        at vg.civcraft.mc.civmodcore.command.CommandHandler.execute(CommandHandler.java:26) ~[?:?]
        at vg.civcraft.mc.civmodcore.ACivMod.onCommand(ACivMod.java:66) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-e0e1771-5e5cf84]
        ... 15 more

**Comment by rourke750** [comment]
Shouldnt happen.  Most likely fixed here https://github.com/Civcraft/PrisonPearl/pull/174
