### ISSUE TITLE
Issue compiling the plugin

### ISSUE THREAD

**Issue by Ninniy** [Civcraft/PrisonPearl#179]
I'm not sure how much information you need, here's the errors

[ERROR] Failed to execute goal on project PrisonPearl: Could not resolve dependencies for project com.untamedears:PrisonPearl:jar:3.0.94: The following artifacts could not be resolved: org.spigotmc:Spigot:jar:1.10, com.wimbli:WorldBorder:jar:1.8.5: Failure to find org.spigotmc:Spigot:jar:1.10 in http://build.civcraft.co:8080/plugin/repository/everything/ was cached in the local repository, resolution will not be reattempted until the update interval of civcraft-repo has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project PrisonPearl: Could not resolve dependencies for project com.untamedears:PrisonPearl:jar:3.0.94: The following artifacts could not be resolved: org.spigotmc:Spigot:jar:1.10, com.wimbli:WorldBorder:jar:1.8.5: Failure to find org.spigotmc:Spigot:jar:1.10 in http://build.civcraft.co:8080/plugin/repository/everything/ was cached in the local repository, resolution will not be reattempted until the update interval of civcraft-repo has elapsed or updates are forced
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.untamedears:PrisonPearl:jar:3.0.94: The following artifacts could not be resolved: org.spigotmc:Spigot:jar:1.10, com.wimbli:WorldBorder:jar:1.8.5: Failure to find org.spigotmc:Spigot:jar:1.10 in http://build.civcraft.co:8080/plugin/repository/everything/ was cached in the local repository, resolution will not be reattempted until the update interval of civcraft-repo has elapsed or updates are forced
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        ... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.spigotmc:Spigot:jar:1.10, com.wimbli:WorldBorder:jar:1.8.5: Failure to find org.spigotmc:Spigot:jar:1.10 in http://build.civcraft.co:8080/plugin/repository/everything/ was cached in the local repository, resolution will not be reattempted until the update interval of civcraft-repo has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
        ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.spigotmc:Spigot:jar:1.10, com.wimbli:WorldBorder:jar:1.8.5: Failure to find org.spigotmc:Spigot:jar:1.10 in http://build.civcraft.co:8080/plugin/repository/everything/ was cached in the local repository, resolution will not be reattempted until the update interval of civcraft-repo has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
        ... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.spigotmc:Spigot:jar:1.10 in http://build.civcraft.co:8080/plugin/repository/everything/ was cached in the local repository, resolution will not be reattempted until the update interval of civcraft-repo has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 27 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by rourke750** [comment]
Yea this one is a little tricky to compile locally cause we use some local maven repos for some plugins that dont have them.  First off do have spigot1.10.0 built locally?  Also @Maxopoly you have some experience doing that.

Then youre going to need a copy of world border and need to maven that.

**Comment by Ninniy** [comment]
I just downloaded a build off of the jenkins, but I thought I'd let you know about it. I didn't know that you knew about it already.

**Comment by rourke750** [comment]
ah Thanks.  Ever since the dnca all of this stuff has been way more difficult

**Comment by Maxopoly** [comment]
Just get worldborder here: https://dev.bukkit.org/media/files/937/149/WorldBorder.jar

And modify the dependency to point at your local jar
