### ISSUE TITLE
Stack trace on /pplocate

### ISSUE THREAD

**Issue by ttk2** [Civcraft/PrisonPearl#30]
2015-02-01 10:24:39 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'pplocate' in plugin PrisonPearl v2.2.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.NullPointerException
        at com.untamedears.PrisonPearl.PrisonPearl.verifyHolder(PrisonPearl.java:284) ~[?:?]
        at com.untamedears.PrisonPearl.PrisonPearl.verifyLocation(PrisonPearl.java:301) ~[?:?]
        at com.untamedears.PrisonPearl.PrisonPearlCommands.locateCmd(PrisonPearlCommands.java:428) ~[?:?]
        at com.untamedears.PrisonPearl.PrisonPearlCommands.onCommand(PrisonPearlCommands.java:44) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 13 more
>2015-02-01 10:24:39,636 ERROR An exception occurred processing Appender LogSnoopHandler java.lang.NullPointerException
        at com.untamedears.MiscLog.LogSnoopHandler.append(LogSnoopHandler.java:66)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
        at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:609)
        at org.bukkit.craftbukkit.v1_7_R4.util.ForwardLogHandler.publish(ForwardLogHandler.java:33)
        at java.util.logging.Logger.log(Logger.java:616)
        at java.util.logging.Logger.doLog(Logger.java:641)
        at java.util.logging.Logger.log(Logger.java:730)
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1019)
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850)
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850)                                                                                  [15/9557]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184)
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/commit/b4d66ab67b79d1265e4a1c78ff00b7394fdf27ff

**Comment by rourke750** [comment]
@ttk2 new jar
