### ISSUE TITLE
/ppimprisonany states "You've bound null to a prison pearl!"

### ISSUE THREAD

**Issue by erocs** [Civcraft/PrisonPearl#40]
Using ppimprisonany on this player returns the message "You've bound null to a prison pearl!" and "An internal error occurred while attempting to perform this command". A pearl is created in the inventory and it does have the correct UUID in the lore. The player name in the lore is set to null though. I'm unsure whether or not this is a valid pearl.

I originally only had 1 slot open on my hot bar. Upon opening another slot open in my inventory the exception disappeared but the pearl is still for a player named "null".

Console shows this exception when I only had a hotbar slot open and no inventory slot open.
2015-04-10 01:06:24 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'ppimprisonany' in plugin PrisonPearl v2.3.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at net.minecraft.server.v1_7_R4.PlayerInventory.setItem(PlayerInventory.java:331) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftInventory.setItem(CraftInventory.java:82) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at com.untamedears.PrisonPearl.managers.PrisonPearlManager.imprisonPlayer(PrisonPearlManager.java:188) ~[?:?]
        at com.untamedears.PrisonPearl.PrisonPearlCommands.imprisonCmd(PrisonPearlCommands.java:505) ~[?:?]
        at com.untamedears.PrisonPearl.PrisonPearlCommands.onCommand(PrisonPearlCommands.java:91) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 13 more

Probably two separate issues. One for the inventory and another for the "null" player.

**Comment by rourke750** [comment]
I'm guessing the player was offline during the time?

**Comment by erocs** [comment]
Probably but unknown.

**Comment by rourke750** [comment]
Maybe a bukkit bug?  Anyways are you sure the playername is correct / in mysql?

**Comment by rourke750** [comment]
bump

**Comment by suirad** [comment]
Pull Submitted, please review

**Comment by suirad** [comment]
Pull merged, please close.
