### ISSUE TITLE
2015-04-26 08:19:33 [ERROR] Could not pass event NpcDespawnEvent to PrisonPearl v2.4.0 (occurred on CIvtest)

### ISSUE THREAD

**Issue by ttk2** [Civcraft/PrisonPearl#42]
2015-04-26 08:19:33 [ERROR] Could not pass event NpcDespawnEvent to PrisonPearl v2.4.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at com.trc202.CombatTag.CombatTag.despawnNPC(CombatTag.java:217) [CombatTag.jar:?]
        at com.trc202.CombatTag.CombatTag$1.run(CombatTag.java:420) [CombatTag.jar:?]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.NoSuchMethodError: com.trc202.CombatTagEvents.NpcDespawnEvent.getNpc()Lcom/topcat/npclib/entity/NPC;
        at com.untamedears.PrisonPearl.CombatTagListener.onNpcDespawn(CombatTagListener.java:30) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        ... 12 more

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/tree/1.8.3

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/commit/19630199f3eed74dadfdaca63a2ffd4d13d2b249

**Comment by rourke750** [comment]
http://192.99.169.83:8080/job/PrisonPearl-dev/23/

**Comment by ttk2** [comment]
on civtest.
