### ISSUE TITLE
Could not pass event PrisonPearlEvent to PrisonPearl v2.4.0 org.bukkit.event.EventException on Civtest

### ISSUE THREAD

**Issue by ttk2** [Civcraft/PrisonPearl#43]
2015-05-09 11:10:55 [ERROR] Could not pass event PrisonPearlEvent to PrisonPearl v2.4.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at com.untamedears.PrisonPearl.managers.PrisonPearlManager.prisonPearlEvent(PrisonPearlManager.java:751) [PrisonPearl-2.4.0.jar:?]
        at com.untamedears.PrisonPearl.managers.PrisonPearlManager.imprisonPlayer(PrisonPearlManager.java:166) [PrisonPearl-2.4.0.jar:?]
        at com.untamedears.PrisonPearl.PrisonPearlPlugin.onEntityDeath(PrisonPearlPlugin.java:586) [PrisonPearl-2.4.0.jar:?]
        at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:382) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.EntityPlayer.die(EntityPlayer.java:417) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.EntityLiving.damageEntity(EntityLiving.java:811) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.EntityHuman.damageEntity(EntityHuman.java:800) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.EntityHuman.attack(EntityHuman.java:1001) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.EntityPlayer.attack(EntityPlayer.java:1060) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:1345) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:52) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:11) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.NullPointerException                                                                                                                               [0/9903]
        at com.untamedears.PrisonPearl.managers.PrisonPortaledPlayerManager.onPrisonPearlEvent(PrisonPortaledPlayerManager.java:132) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        ... 32 more

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/commit/7b03ea0c42153a7e9f00ec76436df0933f6befd0

**Comment by ttk2** [comment]
should I updated PP on Civtest?

**Comment by ttk2** [comment]
oh that build failed.

**Comment by rourke750** [comment]
Yes

**Comment by rourke750** [comment]
Of course.  I'll look tomorrow.
