### ISSUE TITLE
PrisonPearl rewrite using uuids as the identifying factor instead of damage value.

### ISSUE THREAD

**Issue by rourke750** [Civcraft/PrisonPearl#60]
Basically prison pearl differentiates the pearls based on what their damage value is.  This is no longer a viable solution.  We need to move it over to identifying pearls by its first line of lore which should be its uuid.

@gipsy-king I'm assigning you to do this, is that okay?

**Comment by ProgrammerDan** [comment]
'tis a big one. Apparently we've got what, two tiers of backwards compatibility to maintain unless we can upconvert all pearls? (pre-uuid pearls, post-uuid pearls, and with this, lored pearls)

**Comment by rourke750** [comment]
Well you just add another step to the preexisting script.

**Comment by ttk2** [comment]
prisonpearl should touch every pearl every restart thanks to pearl feeding, anyone running prisonpearl recently should have all their pearls on the latest version, unless we want to care about people jumping from really old PP to modern PP without any issues.

**Comment by ProgrammerDan** [comment]
Meant by my comment that I've got reports from Eden that some of their pearls are so old they don't have UUID's. Meaning actively pearls on Civcraft currently span versions.

**Comment by rourke750** [comment]
That's just the lore, good catch though.  Need to make sure that it is
actually there.

**Comment by ttk2** [comment]
shouldn't the pearl be updated when they pick it up?

**Comment by rourke750** [comment]
@gipsy-king how goes this?

**Comment by ttk2** [comment]
Not really apparently.

**Comment by gipsy-king** [comment]
didn't look into PP at all, sorry for not telling you.

**Comment by rourke750** [comment]
NP. I'll start it if you'd rather me.

**Comment by gipsy-king** [comment]
@rourke750 yeah I checked it out and I don't really understand most of PP.

**Comment by erocs** [comment]
Status? Isn't this live?

**Comment by ttk2** [comment]
it died, I think roruke fixed it but I have not tried again since the last debacle.

**Comment by ttk2** [comment]
@rourke750  did you make any improvements here? Should we try again?

**Comment by ttk2** [comment]
just tried again on a local copy, another failure, here is the stack. 

[12:17:24 ERROR]: Error occurred while enabling PrisonPearl v2.5.5 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: 3
        at com.untamedears.PrisonPearl.PrisonPearlStorage.load(PrisonPearlStorage.java:106) ~[?:?]
        at com.untamedears.PrisonPearl.PrisonPearlPlugin.load(PrisonPearlPlugin.java:429) ~[?:?]
        at com.untamedears.PrisonPearl.PrisonPearlPlugin.onEnable(PrisonPearlPlugin.java:129) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by erocs** [comment]
@rourke750 status?
