### ISSUE TITLE
Can't ppunban user

### ISSUE THREAD

**Issue by ttk2** [Civcraft/PrisonPearl#61]
>ppunban USERNAME
2015-08-02 15:17:46 [ERROR] Could not pass event RequestAltsListEvent to MiscLog v0.6.24
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
        at com.untamedears.PrisonPearl.AltsList.queryForUpdatedAltLists(AltsList.java:80) [PrisonPearl-2.4.4.jar:?]
        at com.untamedears.PrisonPearl.AltsList.getAltsArray(AltsList.java:101) [PrisonPearl-2.4.4.jar:?]
        at com.untamedears.PrisonPearl.PrisonPearlCommands.unBanAlt(PrisonPearlCommands.java:293) [PrisonPearl-2.4.4.jar:?]
        at com.untamedears.PrisonPearl.PrisonPearlCommands.onCommand(PrisonPearlCommands.java:231) [PrisonPearl-2.4.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:626) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:411) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-f94fe8f-d27e6d0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
        at com.untamedears.MiscLog.EventListener.onRequestAltsListEvent(EventListener.java:216) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor193.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f94fe8f-d27e6d0]
        ... 16 more
2015-08-02 15:17:46 [INFO] 1 accounts were unbanned or left alone.

**Comment by erocs** [comment]
The NPE is either a null event object when calling RequestAltsListEvent.getPlayersToCheck() or there's a null UUID returned in that list, probably the latter.

**Comment by erocs** [comment]
The player he ran the command against does exist in Name_player. The account has been Mojang renamed away from the name enforced by NameLayer. The account was alt-banned, but I fixed that for Ttk2.
