### ISSUE TITLE
NullPointerException in WorldBorderManager.isMaxFeed

### ISSUE THREAD

**Issue by erocs** [Civcraft/PrisonPearl#79]
2015-11-17 03:39:45 [ERROR] Error occurred while enabling PrisonPearl v2.5.99 (Is it up to date?)
java.lang.NullPointerException
        at com.untamedears.PrisonPearl.managers.WorldBorderManager.isMaxFeed(WorldBorderManager.java:42) ~[?:?]
        at com.untamedears.PrisonPearl.PrisonPearlStorage.feedPearls(PrisonPearlStorage.java:436) ~[?:?]
        at com.untamedears.PrisonPearl.PrisonPearlPlugin.onEnable(PrisonPearlPlugin.java:177) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by Maxopoly** [comment]
Was this when bungee was enabled?

**Comment by erocs** [comment]
Restart last night after the disk full issue was resolved.

**Comment by Maxopoly** [comment]
It must have overwritten/fucked up something somewhere. We could catch that error at the cost of the whole WorldBorderManager to keep PP itself running, but this is most likely a config/naming error, so I think it would make sense to throw an exception and not just try to bypass it.

I assume it was fixed after some space was freed up?

**Comment by TealNerd** [comment]
So I guess this isn't really an issue?

**Comment by Maxopoly** [comment]
Most likely not
