### ISSUE TITLE
Cross server summoning does not work 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/PrisonPearl#82]
[13:40:22 ERROR]: null                                                                                                                          │·······························
org.bukkit.command.CommandException: Unhandled exception executing command 'pps' in plugin PrisonPearl v2.6.24                                  │·······························
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-d97e08b-880a532]                             │·······························
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-d97e08b-880a532]                     │·······························
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-d97e08b-880a532]            │·······························
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-d97e08b-880a532]      │·······························
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-d97e08b-880a532]                   │·······························
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-d97e08b-880a532]                    │·······························
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-d97e08b-880a532]                     │·······························
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d97e08b-880a532]                      │·······························
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]                                        │·······························
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]                                                       │·······························
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-d97e08b-880a532]                                    │·······························
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-d97e08b-880a532]                     │·······························
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-d97e08b-880a532]                     │·······························
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-d97e08b-880a532]                     │·······························
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-d97e08b-880a532]                   │·······························
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]                                                                          │·······························
Caused by: java.lang.NullPointerException                                                                                                       │·······························
        at com.untamedears.PrisonPearl.managers.CombatTagManager.isCombatTagged(CombatTagManager.java:54) ~[?:?]                                │·······························
        at com.untamedears.PrisonPearl.managers.CombatTagManager.isCombatTagged(CombatTagManager.java:59) ~[?:?]                                │·······························
        at com.untamedears.PrisonPearl.PrisonPearlPlugin.isCombatTagged(PrisonPearlPlugin.java:1008) ~[?:?]                                     │·······························
        at com.untamedears.PrisonPearl.PrisonPearlCommands.summonCmd(PrisonPearlCommands.java:644) ~[?:?]                                       │·······························
        at com.untamedears.PrisonPearl.PrisonPearlCommands.onCommand(PrisonPearlCommands.java:83) ~[?:?]                                        │·······························
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-d97e08b-880a532]                             │·······························
        ... 15 more

**Comment by rourke750** [comment]
I mean it doesnt work but not from this error now :/
