### ISSUE TITLE
Stack on locate any

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/PrisonPearl#97]
Caused by: java.lang.NullPointerException                                                                                                                                       │····························································        at vg.civcraft.mc.prisonpearl.managers.PrisonPearlManager.freePearlFromMercury(PrisonPearlManager.java:407) ~[?:?]                                                      │····························································        at vg.civcraft.mc.prisonpearl.listener.MercuryListener.pearlUpdate(MercuryListener.java:110) ~[?:?]                                                                     │····························································
        at vg.civcraft.mc.prisonpearl.listener.MercuryListener.mercuryListener(MercuryListener.java:53) ~[?:?]                                                                  │····························································        at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source) ~[?:?]                                                                                                  │····························································        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]                                                         │····························································
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]                                                                                              │····························································        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-880a532]                                                │····························································        ... 11 more

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/commit/38376b0929374c6266a022ffed7075e88a49b062
