### ISSUE TITLE
Stack on playerinteract

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/PrisonPearl#98]
Caused by: java.lang.NullPointerException                                                                                                                                       │····························································        at vg.civcraft.mc.prisonpearl.managers.PrisonPearlManager.freePearl(PrisonPearlManager.java:248) ~[?:?]                                                                 │····························································
        at vg.civcraft.mc.prisonpearl.listener.PlayerListener.freePearl(PlayerListener.java:695) ~[?:?]                                                                         │····························································        at vg.civcraft.mc.prisonpearl.listener.PlayerListener.onPlayerInteract(PlayerListener.java:673) ~[?:?]                                                                  │····························································        at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source) ~[?:?]                                                                                                  │····························································
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]                                                         │····························································        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]                                                                                              │····························································        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-880a532]                                                │····························································
        ... 17 more

**Comment by KillerSmurf** [comment]
Working on this issue currently.

**Comment by rourke750** [comment]
No need, I'll fix this with my other updates.
